sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE_test=glumac/rsolab2:0.1

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE_test" .

after_success:
  - echo "$DOCKER_PASSWORD_test" | docker login -u "$DOCKER_USERNAME_test" --password-stdin
  - docker push "$DOCKER_IMAGE_test"
