apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-users
          env:
            - name: POSTGRESQL_USER
              value: dbuser
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: user
          ports:
          - containerPort: 5433 #previous 5432
            protocol: TCP