apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  type: ClusterIP
  ports:
  - port: 5433 #previous 5432
    protocol: TCP
    targetPort: 5433 #previous 5432
  selector:
    app: postgres-user